version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: board-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
